apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      run: ingress-nginx
  template:
    metadata:
      labels:
        run: ingress-nginx
    spec:
      containers:
      - image: nginx
        name: ingress-nginx
        ports:
        - containerPort: 80
